# Generated by Django 5.2.5 on 2025-08-30 08:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_comment_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='author_name',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='transcript',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='artisan',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='story',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='story',
            name='category',
        ),
        migrations.RemoveField(
            model_name='story',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='story',
            name='location',
        ),
        migrations.RemoveField(
            model_name='story',
            name='tags',
        ),
        migrations.AddField(
            model_name='artisan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treeplanting',
            name='actually_planted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treeplanting',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending - Promise Made'), ('planted', 'Planted - Tree in Ground'), ('verified', 'Verified - Tree Checked'), ('failed', 'Failed - Couldn’t Plant')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='community',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artisan_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='story',
            name='artisan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='stories.artisan'),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='treeplanting',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='treeplanting',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='treeplanting',
            name='planted_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='treeplanting',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_plantings', to='stories.story'),
        ),
    ]
