# Generated by Django 5.2.5 on 2025-08-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_category_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
