# Generated by Django 5.2.5 on 2025-08-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_event_rename_name_comment_author_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treeplanting',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente - Promesse faite'), ('planted', 'Plante - Arbre en terre'), ('verified', 'Verifie - Arbre controle'), ('failed', 'Echoue - Impossible de planter')], default='pending', max_length=10),
        ),
    ]
